Chris 1st Round of Changes 2021

diff --git a/bin/install_app_store b/bin/install_app_store
--- a/bin/install_app_store
+++ b/bin/install_app_store
@@ -2,116 +2,44 @@
 
 # Installs App Store software.
 
-# 1Password
-mas install 443987910
-
-# Acorn
-mas install 1547371478
-
-# AquaPath
-mas install 424425207
-
-# Bear
-mas install 1091189122
-
-# Cocoa JSON Editor
-mas install 442160773
-
-# Contrast
-mas install 1254981365
-
-# DaisyDisk
-mas install 411643860
-
-# GarageBand
-mas install 682658836
-
-# Hand Mirror
-mas install 1502839586
-
-# iMovie
-mas install 408981434
-
-# Kaleidoscope
-mas install 587512244
-
-# Key Codes
-mas install 414568915
-
-# Keymou
-mas install 449863619
+if ! command -v mas > /dev/null; then
+  printf "ERROR: Mac App Store CLI (mas) can't be found.\n"
+  printf "       Please ensure Homebrew and mas (i.e. brew install mas) have been installed first."
+  exit 1
+fi
 
 # Keynote
 mas install 409183694
 
-# Kindle
-mas install 405399194
-
-# Leech
-mas install 1101735327
-
-# LimeChat
-mas install 414030210
-
-# Marked 2
-mas install 890031187
-
-# Medis
-mas install 1063631769
-
-# Meeter
-mas install 1510445899
-
-# MindNode
-mas install 1289197285
-
-# MoneyWell
-mas install 404246493
-
-# Moom
-mas install 419330170
-
-# Name Mangler
-mas install 603637384
-
 # Numbers
 mas install 409203825
-
-# OmniFocus 3
-mas install 1346203938
-
-# OmniOutliner
-mas install 404478020
 
 # Pages
 mas install 409201541
 
-# Patterns
-mas install 429449079
+# cleaner-one-disk-clean
+mas install 1133028347
 
-# PDFpenPro
-mas install 403758325
+# fast-mbox-editor
+mas install 1444529635
 
-# Pixelmator
-mas install 407963104
+# magnet
+mas install 441258766
 
-# Paletter
-mas install 1494948845
+# microsoft-remote-desktop
+mas install 1295203466
 
-# Primitive
-mas install 1175103038
+# monday-com
+mas install 1298450641
 
-# Sequence Diagram
-mas install 1195426709
+# gif-brewery-3-by-gfycat
+mas install 1081413713
 
-# Shush
-mas install 496437906
+# apple-remote-desktop
+mas install 409907375
 
-# Slack
-mas install 803453959
+# blackmagic-disk-speed-test
+mas install 425264550
 
-# TextSniper
-mas install 1528890965
-
-# WiFi Explorer
-mas install 494803304
+# compressor
+mas install 424390742
